AWSTemplateFormatVersion: '2010-09-09'
Description: Gateway VPC Endpoint for Amazon S3

Parameters:
  ProjectName:
    Type: String
    Description: Project name prefix for resource naming

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the endpoint will be created

Resources:
  S3GatewayVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref VpcId
      VpcEndpointType: Gateway
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-s3-gateway-endpoint"

Outputs:
  S3VpcEndpointId:
    Description: The ID of the S3 Gateway VPC Endpoint
    Value: !Ref S3GatewayVpcEndpoint
    Export:
      Name: !Sub "${ProjectName}-S3VpcEndpointId"