name: GitOps CloudFormation Deployment

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::975050199901:role/Github_web_identity
        aws-region: ap-southeast-1

    - name: Install Python dependencies
      run: |
        pip install boto3 cryptography

    - name: Run deployment script
      run: |
        python deployment.py
